package io.github.cursoms.msavaliadorcredito.application.exception;

public class DadosClienteNotFoundException extends RuntimeException{
    public DadosClienteNotFoundException() {
        super("Dados do cliente n√£o encontrado para o CPF informado.");
    }
}
